---
name: "Publish to PyPI"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pypi-publish:
    name: PyPI Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install --upgrade build twine
          python -m build --sdist --wheel --outdir dist/
          python -m twine upload --skip-existing dist/*
